sudo: required
language: java
jdk:
 - oraclejdk8
services:
 - docker
before_install:
 - chmod +x mvnw
script:
 - ./mvnw clean install -B
 after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: backendspringboot