sudo: required
language: java
jdk:
 - oraclejdk8
services:
 - docker
before_install:
 - chmod +x mvnw
script:
 - ./mvnw clean install -B
after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - docker build -t $IMAGE_NAME .
 - docker tag image $DOCKER_USER/$IMAGE_NAME:$TAG
 - docker push $DOCKER_USER/$IMAGE_NAME:$TAG
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: backendspringboot